import type { Metadata } from "next";
import { Fredoka, Poppins  } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const fredoka = Fredoka({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Pesos que necesitas
  variable: "--font-fredoka",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"], 
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fredoka.variable} ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
